name: zefyr_apex
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter. Fork with zefyr and apex make it better.
version: 2.0.0
homepage: https://gitlab.com/apexzefyr/zefyr

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^6.0.4
  notus_apex: ^1.0.0
  quill_delta: ^2.0.0
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  characters: ^1.0.0
  image_picker: ^0.7.5+2
  video_player: ^2.1.1
  file_picker: ^3.0.1
  video_thumbnail: ^0.3.3
  mime: ^1.0.0
  just_audio: ^0.7.4+1
  modal_bottom_sheet: ^2.0.0
  emojis: ^0.9.3
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  syncfusion_flutter_datepicker: ^19.1.64-beta
  syncfusion_flutter_core: ^19.1.64
  solar_datepicker: ^0.1.0
  shamsi_date: ^0.12.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
